"""
Django settings for catloads project.

Generated by 'django-admin startproject' using Django 4.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# LOGGING = {
#     'version': 1,
#     'disable_existing_loggers': False,
#     'handlers': {
#         'console': {
#             'level': 'DEBUG',
#             'class': 'logging.StreamHandler',
#         },
#     },
#     'loggers': {
#         'django': {
#             'handlers': ['console'],
#             'level': 'DEBUG',
#         },
#         '__main__': {
#             'handlers': ['console'],
#             'level': 'DEBUG',
#         },
#     },
# }


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-j9_@c%1_sz#i#nqfluyd9h=&fkj%adcad@e5q=4!y#v+qhy71q'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

SITE_ID = 3

ALLOWED_HOSTS = ['*']

LOGIN_URL = '/admin/login'
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django_extensions',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'catloads_web',
    'catloads_admimn',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.facebook',
    'django_ckeditor_5'

]

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        }
    }
}


SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_LOGIN_ON_GET =True

# Optional: This automatically logs in the user upon signup
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True

# This is also often helpful; it logs in the user on email confirmation
ACCOUNT_SESSION_REMEMBER = True

ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False

ACCOUNT_AUTHENTICATION_METHOD = 'email'

SOCIALACCOUNT_ADAPTER = 'catloads_web.adapter.MySocialAccountAdapter'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    "catloads_admimn.middleware.GeoIPMiddleware"
]

ROOT_URLCONF = 'catloads.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'catloads_admimn.context_processors.get_countries'
                
            ],
        },
    },
]

WSGI_APPLICATION = 'catloads.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}



# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

DATA_UPLOAD_MAX_MEMORY_SIZE = 20 * 1024 * 1024  # 10 MB

SESSION_COOKIE_AGE = 60 * 60 * 24 #1Day

# SECURE_CROSS_ORIGIN_OPENER_POLICY = "same-origin-allow-popups"

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
)

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'As'

USE_I18N = True

USE_TZ = True

TIME_ZONE = 'Asia/Calcutta'

AUTH_USER_MODEL = 'catloads_web.CustomUser'

RAZOR_PAY_KEY = "rzp_test_JsXnTn63V5HMtu"

RAZOR_PAY_SECRET = "eCRinwb8kkxDsH5u9ixPHLpi"
RAZO_PAY_WEBHOOK = "0bb619d97e8ddc205e39b0736b293452ef242c7156f05f524d8907d7474673a1"

LOGIN_REDIRECT_URL = '/login/redirect'

TWILIO_ACCOUNT_SID = ''
TWILIO_AUTH_TOKEN = ''
TWILIO_PHONE_NUMBER = '+917907991534'

PASSWORD_RESET_TIMEOUT = 7200

GEOIP_PATH = os.path.join(BASE_DIR, 'geoip2')

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

MEDIA_URL   = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR,'media')

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

META_ACCESSTOKEN = "EAAMTNultbiYBO8cQj6JHm1TEm0lLEFb6NjMPK7dzYczjW5ZAxdnf5ITPx713hamtsF7hryYEL3J9SH8PhvIocatXtATmLzR8kwv9vC8Citig4hoL3YhALZBjOyCKqdH5M98C1EqNaWZC3rsn8XeZBr5Phk2rJLsZC9X83zqAvlP7rRSWgyStFU1UMyOXOGJFYjAZDZD"

PIXEL_ID = '525136436717782'

METAAPI_URL = f'https://graph.facebook.com/v16.0/{PIXEL_ID}/events?access_token={META_ACCESSTOKEN}'

