# Generated by Django 5.0.6 on 2024-05-12 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catloads_web', '0004_alter_banner_created_on_alter_banner_updated_on_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='label',
            new_name='banner_head',
        ),
    ]
