# Generated by Django 5.0.6 on 2024-05-12 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catloads_web', '0005_rename_label_banner_banner_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(default=0, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='productsale',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
