# Generated by Django 5.0.6 on 2024-05-12 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catloads_web', '0006_order_order_id_alter_productsale_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
