# Generated by Django 5.0.6 on 2024-05-12 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catloads_web', '0007_alter_order_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.IntegerField(blank=True, choices=[(1, 'Pending'), (2, 'Completed'), (2, 'Failed')], default=1, null=True),
        ),
    ]
