# Generated by Django 5.0.6 on 2024-05-13 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catloads_web', '0009_customuser_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsaleitems',
            name='product_images',
        ),
        migrations.RemoveField(
            model_name='productsaleitems',
            name='product_videos',
        ),
        migrations.AlterField(
            model_name='productimages',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_images', to='catloads_web.productsale'),
        ),
        migrations.AlterField(
            model_name='productvideos',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productssale_videos', to='catloads_web.productsale'),
        ),
    ]
