# Generated by Django 5.0.6 on 2024-05-13 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catloads_web', '0010_remove_productsaleitems_product_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsale',
            name='sale_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
