# Generated by Django 5.0.6 on 2024-05-22 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catloads_web', '0012_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='usertype',
            field=models.IntegerField(choices=[(1, 'ADMIN'), (2, 'CUSTOMER')], default=2),
        ),
    ]
