# Generated by Django 5.0.6 on 2024-05-24 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catloads_web', '0013_alter_customuser_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
