# Generated by Django 5.0.6 on 2024-06-03 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catloads_web', '0015_alter_order_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsale',
            name='razorpay_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.IntegerField(blank=True, choices=[(1, 'Pending'), (2, 'Completed'), (3, 'Failed')], default=1, null=True),
        ),
    ]
