# Generated by Django 5.0.6 on 2024-06-03 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catloads_web', '0016_productsale_razorpay_id_alter_order_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsale',
            name='razorpay_id',
        ),
        migrations.AddField(
            model_name='order',
            name='razorpay_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
