# Generated by Django 5.0.6 on 2024-06-04 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catloads_web', '0017_remove_productsale_razorpay_id_order_razorpay_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='signature',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
