# Generated by Django 5.0.6 on 2024-06-19 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catloads_web', '0019_alter_payment_amount_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimages',
            name='upload_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productvideos',
            name='upload_order',
            field=models.IntegerField(default=0),
        ),
    ]
