# Generated by Django 5.0.6 on 2024-06-21 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catloads_web', '0020_productimages_upload_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
