# Generated by Django 5.0.6 on 2024-06-24 08:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catloads_web', '0021_customuser_created_on_customuser_updated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsale',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
