# Generated by Django 5.0.6 on 2024-06-24 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catloads_web', '0026_alter_productsale_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsale',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
