# Generated by Django 5.0.6 on 2024-06-24 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catloads_web', '0027_productsale_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsale',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10, null=True),
        ),
    ]
