# Generated by Django 5.0.6 on 2024-06-27 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catloads_web', '0028_alter_productsale_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sale_tag',
            field=models.CharField(default='LIMITED SALE', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_tag_color',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
