# Generated by Django 5.0.6 on 2024-06-27 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catloads_web', '0029_product_sale_tag_product_sale_tag_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sale_tag',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sale_tag_color',
        ),
        migrations.AddField(
            model_name='productsale',
            name='sale_tag',
            field=models.CharField(default='LIMITED SALE', max_length=255),
        ),
        migrations.AddField(
            model_name='productsale',
            name='sale_tag_color',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
