# Generated by Django 5.0.6 on 2024-06-27 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catloads_web', '0030_remove_product_sale_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsale',
            name='sale_tag_color',
            field=models.CharField(default='#FF0000', max_length=255, null=True),
        ),
    ]
