# Generated by Django 5.0.6 on 2024-07-08 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catloads_web', '0031_alter_productsale_sale_tag_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='reason',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.IntegerField(blank=True, choices=[(1, 'Online'), (2, 'Paypal')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
