# Generated by Django 5.0.6 on 2024-08-21 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catloads_web', '0034_country_countryprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsale',
            name='countries',
            field=models.ManyToManyField(related_name='product_countries', through='catloads_web.CountryPrice', to='catloads_web.country'),
        ),
    ]
