# Generated by Django 5.0.6 on 2024-09-20 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catloads_web', '0037_country_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='countryprice',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
