# Generated by Django 5.0.6 on 2024-09-20 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catloads_web', '0038_country_default_countryprice_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='symbol',
            field=models.CharField(default='$', max_length=10),
        ),
    ]
