# Generated by Django 5.0.6 on 2024-09-20 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catloads_web', '0039_alter_country_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catloads_web.country'),
        ),
        migrations.AddField(
            model_name='order',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catloads_web.country'),
        ),
    ]
