# Generated by Django 5.0.6 on 2024-10-05 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catloads_web', '0043_authtoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authtoken',
            old_name='name',
            new_name='user',
        ),
    ]
