# Generated by Django 5.0.6 on 2024-10-10 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catloads_web', '0044_rename_name_authtoken_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client_ip_address',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='client_user_agent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
