# Generated by Django 5.0.6 on 2024-10-10 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catloads_web', '0045_order_client_ip_address_order_client_user_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fcb_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
